BOT: AI_BayMax_bot
  TOKEN: 7304651415:AAHJvc5FacF0UIfROjAWwalAY7C4lib8Ew4  # Get your bot token from @BotFater
AI:
  VERSION: "2023-03-15-preview"
  TYPE: "azure"
  MODEL: "azure"
  BASE: "https://docs-test-001.openai.azure.com/"
  TOKEN: "7304651415:AAHJvc5FacF0UIfROjAWwalAY7C4lib8Ew4"
MYSQL:
  DBHOST: 127.0.0.1
  DBPORT: 3306
  DBUSER: root
  DBPWD: dbpassword
  DBNAME: database_name
  DBCHAR: utf8mb4

RATE_LIMIT:
  0: 10
  1: 30
  2: 300

CONTEXT_COUNT:
  0: 3
  1: 5
  2: 10

MAX_TOKEN:
  0: 256
  1: 1024
  2: 1024

TIME_SPAN: 3 #Minutes
DEVELOPER_CHAT_ID: 5420271423
